In [1]:
import pandas as pd 
from sklearn.model_selection import train_test_split

Load The Dataset & Understanding the Dataset

In [ ]:
df = pd.read_csv(r"C:\Users\Asus\Downloads\500hits.csv"  , encoding = 'latin-1')
df.head() #

         PLAYER  YRS     G     AB     R     H  ...    BB    SO   SB   CS     BA  HOF
0       Ty Cobb   24  3035  11434  2246  4189  ...  1249   357  892  178  0.366    1
1   Stan Musial   22  3026  10972  1949  3630  ...  1599   696   78   31  0.331    1
2  Tris Speaker   22  2789  10195  1882  3514  ...  1381   220  432  129  0.345    1
3   Derek Jeter   20  2747  11195  1923  3465  ...  1082  1840  358   97  0.310    1
4  Honus Wagner   21  2792  10430  1736  3430  ...   963   327  722   15  0.329    1

[5 rows x 16 columns]

Creating X and Y Variables

In [10]:
X = df.drop(columns=['PLAYER' ,'HOF']) # Player column utna jruri nahi features me target predict krne ke liye to hata denge aur HOF target hai toh uss se X se hata denge 
X.head()

   YRS     G     AB     R     H   2B  ...   RBI    BB    SO   SB   CS     BA
0   24  3035  11434  2246  4189  724  ...   726  1249   357  892  178  0.366
1   22  3026  10972  1949  3630  725  ...  1951  1599   696   78   31  0.331
2   22  2789  10195  1882  3514  792  ...   724  1381   220  432  129  0.345
3   20  2747  11195  1923  3465  544  ...  1311  1082  1840  358   97  0.310
4   21  2792  10430  1736  3430  640  ...     0   963   327  722   15  0.329

[5 rows x 14 columns]

In [11]:
y = df['HOF'] 
y.head()

0    1
1    1
2    1
3    1
4    1
Name: HOF, dtype: int64

Implementing Train test Split

In [ ]:
X_train , X_test , y_train , y_test = train_test_split(X , y , random_state=11 , test_size= 0.2)
# random_state ek fixed seed hai jo ensure karta hai ki same code dobara run karne par data har baar same tarike se train aur test me split ho,
#Agar kissi ne same dataset + same code + same random_state=11 use kiya → exact same train-test split milega 
#test_size define karta hai ki data ka kitna portion model ko test karne ke liye alag rakha jayega ,
# 0.2 = 20% data → test set , 80% data → train set

Verifying the data Split

In [16]:
X_test.shape

(93, 14)

In [15]:
X_train.shape

(372, 14)

In [17]:
y_test.shape

(93,)

In [18]:
y_train.shape

(372,)

Exploring The Training Data

In [21]:
X_train.head()

     YRS     G    AB     R     H   2B  ...   RBI    BB    SO   SB   CS     BA
289   18  2028  7298   873  1993  284  ...  1163   620  1313   20   38  0.273
288   13  1836  6826   856  1996  392  ...   402   513   360  247  108  0.292
350   14  1799  6373   876  1854  282  ...   630   844   627   37   51  0.291
196   17  2158  7911  1057  2276  414  ...   844   690   784  246  138  0.288
184   19  2390  8570  1386  2369  420  ...  1084  1197  1099  143   75  0.276

[5 rows x 14 columns]

Compairing Train vs Test statistics

In [20]:
X_train.describe()

              YRS            G  ...          CS          BA
count  372.000000   372.000000  ...  372.000000  372.000000
mean    17.010753  2046.521505  ...   58.986559    0.289164
std      2.662486   351.232903  ...   49.322224    0.021069
min     11.000000  1331.000000  ...    0.000000    0.246000
25%     15.000000  1797.500000  ...   23.000000    0.274000
50%     17.000000  1992.000000  ...   52.000000    0.288000
75%     19.000000  2245.500000  ...   84.000000    0.300250
max     26.000000  3308.000000  ...  335.000000    0.366000

[8 rows x 14 columns]

In [22]:
X_test.describe()

             YRS            G            AB  ...          SB          CS         BA
count  93.000000    93.000000     93.000000  ...   93.000000   93.000000  93.000000
mean   17.204301  2057.408602   7452.967742  ...  191.817204   54.473118   0.286903
std     3.153877   368.580421   1265.371087  ...  166.925976   42.508462   0.021776
min    11.000000  1399.000000   5472.000000  ...    8.000000    0.000000   0.248000
25%    15.000000  1820.000000   6622.000000  ...   61.000000   15.000000   0.272000
50%    17.000000  1997.000000   7359.000000  ...  137.000000   50.000000   0.285000
75%    19.000000  2282.000000   8096.000000  ...  271.000000   83.000000   0.299000
max    25.000000  2850.000000  10876.000000  ...  744.000000  173.000000   0.340000

[8 rows x 14 columns]

#Hum analysis features (X) ka karte hain kyunki wahi model ke inputs hote hain;
#target (y) sirf prediction ke liye hota hai aur usse train aur evaluation me use karte hain.